name: Build Android APK

on:
  workflow_dispatch:
  push:
    paths:
      - 'flutter_app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter_app
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hod-app-release-apk
          path: flutter_app/build/app/outputs/flutter-apk/app-release.apk


